name: Manual workflow

on:
  pull_request:
    branches:
      - aphrodite
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
